### ISSUE TITLE
Mailer contact form

### ISSUE THREAD

**Issue by gustavotero7** [pimmey/react-docs#1]
Hello, i'm getting the following error when I try to use the contact form

> Something went wrong, try again. Error: [object Object]

I already have setup the config.php file
can you help me?

_purchase code: 8143bc9d-f7f7-4eb1-b43e-078a2dc9e722_

**Comment by pimmey** [comment]
Hi,

Could you please enable debugging - in `mailer/mailer.php` uncomment the line that says:

```
//$mail->SMTPDebug = 2;
```

Then try to capture the error details.

I can also recommend [PHPMailer's troubleshooting wiki](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting) in case you wanna try to solve it on your own.

**Comment by gustavotero7** [comment]
hello, it says 

> build.min.js?v=1.0:3 POST http://gochimera.biz/mailer/mailer.php 404 (Not Found)

but the url to the site is http://gochimera.biz/chimera.digital/home/ not http://gochimera.biz/

you know the reason?

![sin titulo](https://cloud.githubusercontent.com/assets/8619784/17872561/427fa62a-6886-11e6-977a-b015c4894139.png)

**Comment by pimmey** [comment]
Right, the thing is, AJAX call to the mailer is going to `url: '/mailer/mailer.php'`. You can open build.min.js, look for that url and add the correct path, as so:

```
url: '/chimera.digital/home/mailer/mailer.php'
```

Let me know, if that cuts it.

**Comment by gustavotero7** [comment]
Solved, thanks!
