### ISSUE TITLE
Direct link to open modal

### ISSUE THREAD

**Issue by gustavotero7** [pimmey/react-docs#2]
Any way to open a modal direct from a url?
example, myDomain.com/#miModalToOpen

Any idea how to do this?

**Comment by pimmey** [comment]
Yup, something like this should work:

``` js
if (window.location.hash.length > 0 && window.location.hash !== '#!') {
    $(window.location.hash).openModal();
}
```

You're checking for any hash in the url and if it's not `#!`, open a modal based on that hash.

**Comment by gustavotero7** [comment]
cool! thanks!  =D
